### ISSUE TITLE
Creating a New Team

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1084]
**Description:**

1. The user should be able to create a new team by clicking the "+" icon present in the LHS just above the team section. 
2. Once clicked, the user should be presented with a popup containing fields for "Team and Organization Name," "About," and "Logo." 
3. The popup should include descriptions for each field and provide warnings if inputs are incorrect. 
4. Post clicking "Create Team," the user should be able to view a success or failure toast message.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/fa0f7953-50a6-4dfc-b263-cc60d15df274)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is logged in
When the user clicks on the "+" icon above the team section in the LHS
Then a popup should appear for creating a new team.

Acceptance Criteria 2:
Given the popup for creating a new team is displayed
When the user views the popup
Then the popup should include the following fields:

1. Team and Organization Name: An input box for entering the name of the team and organization.
2. About: A text area for providing a description of the team.
3. Logo: An option to upload or select a logo for the team.

Acceptance Criteria 3:

Given the user is in the popup for creating a new team
When the user fills in the required information
Then warnings should appear if any inputs are incorrect or missing.

Acceptance Criteria 4:
Given the user has filled in the required information correctly
When the user clicks on "Create Team"
Then a success or failure toast message should appear confirming the creation of the team.

Acceptance Criteria 5:
Given the user has successfully created the team
When the user closes the popup
Then the new team should appear in the team section on the LHS.

**Comment by itsmdasifraza** [comment]
Pushed to Code Review 
cc: @Monika-APM

**Comment by shreyas070707** [comment]
AC1-
Pop-up is opening


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/c08770e5-a3d7-433f-85aa-e107f81fc18f)

AC2-
Following fields are present in pop-up
Team and Organization Name: An input box for entering the name of the team and organization.
About: A text area for providing a description of the team.
Logo: An option to upload or select a logo for the team.

(icon is present instead of logo, creating bug for same)
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/2396176c-2184-415f-b732-1807d2ed948c)

AC3-
Warning message are present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/ed23809c-50c8-42ef-8e21-8c42d83e53c6)



![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/f4d50e7f-bde4-4565-8c90-886f1410a2a9)

AC4-
"success message" is present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/7b24cfbd-d807-4a5c-a108-67069e0cc1e9)


failure message present
![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/d61e1bda-1096-424d-a9e8-1d00feb3d314)

 AC5-
Newly created team present in LHS


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/099d766e-58cd-40f2-bb95-8cd13c0fdad9)

**Comment by shreyas070707** [comment]
@sanilnayak  please check for the mac

**Comment by sanilnayak** [comment]
Tested the user story in mac and listed down the bugs
