### ISSUE TITLE
Invite Team Members

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#1106]
**Description:**

1. The user should be able to invite members to a Team by clicking on the "Invite" button.
2. After clicking the "Invite" button, a popup should appear containing two fields: "Invite by Email," where the user can enter the email address to add them to the workspace, and "Role," where the user can select the role for the member (Admin/Editor/Viewer).
3. All descriptions and field placements should follow the Figma design. After clicking "Send Invite," the user should see a success or failure message.
4. When a user is trying to invite Member to a team, suppose if there are any validation errors then the validation errors should be displayed on the screen.

**Figma:**

![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/f0d113cc-c3c2-4e4d-83ca-fd7b420cb386)

**Acceptance Criteria:**

Acceptance Criteria 1 [Viewing Sections in Team and Workspace]:
Given The user is in a Team and workspace section of Sparrow application.
When They click on the "Invite" button.
Then A popup should appear for inviting a new member, according to the Figma design.

Acceptance Criteria 2 [Accessing Invite Popup]:
Given The popup for inviting a new member is displayed with cross button for closing the popup.
When The user views the popup.
Then The popup should include the following fields:

- Invite by Email: An input box for entering the email address of the new member, with a description and warnings matching the Figma design.
- Role: A dropdown selection box for choosing the role of the new member (Editor/Viewer/Admin), with a description matching the Figma design
- Workspace: An additional dropdown for selecting the workspace, which appears only if the role is Editor or Viewer.

Acceptance Criteria 3 [Sending Invitation]:
Given The user has entered an email and selected a role.
When They click on "Send Invite."
Then User should be able to click on CTA "Send Invite" & invitation should be sent.

Acceptance Criteria 4 [Invalid Email ID]:
Given the user has entered an email and selected a role.
When the user provides the wrong Email ID
Then, If the email id entered is incorrect, then validation error should be displayed stating "Invalid email address. Please check & enter correct email address.

Acceptance Criteria 5 [Empty Fields Validation]:
Given The user is in the process of inviting a new member.
When The user tries to send an invite with any required field left empty.
Then A validation error should be displayed indicating that the field cannot be left empty.

Acceptance Criteria 6 [Handling Invitation Success]:
Given The user sees a success message.
When They close the popup.
Then User should be able to see the success toast message stating "Invite sent to 'Name' for "Team'".

Acceptance Criteria 7 [Handling Invitation Failure]:
Given The user sees a failure toast message.
When They still want to add member to the team.
Then User should be able to see the failure toast message stating "Failed to sent invite. Please try again.

**Technical Notes (If any):**

**Comment by itsmdasifraza** [comment]
started with invite flow 
cc: @Monika-APM

**Comment by shreyas070707** [comment]
@ayushadhikari93  due to time constraints not able to add screenshots
AC1-
"INVITE" button is present


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/bd717bca-bbde-4421-84e8-bd32a967cf5b)


AC2-
Invite by Email: An input box for entering the email address of the new member, with a description and warnings matching the Figma design.-PRESENT
Role: A dropdown selection box for choosing the role of the new member (Editor/Viewer/Admin), with a description matching the Figma design-ONLY ADMIN ROLE PRESENT
Workspace: An additional dropdown for selecting the workspace, which appears only if the role is Editor or Viewer.- NOT PRESENT


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/97c7628a-bc00-465e-ae33-99c7a29b87ea)

AC3-
User is able to invite single/multiple the member

AC4-
invalid mail validation present
"Invalid email address. Please check & enter correct email address.

AC5-
empty field validation are present for both the fields

AC6-
success message present
"Invite sent" message is coming

AC7-
FAILURE message present for user doesn't exists and member is already present

**Comment by sanilnayak** [comment]
tested in mac and list down the bugs.
