### ISSUE TITLE
Application Update - Update is not happening in Windows machines

### ISSUE THREAD

**Issue by nagesh953** [sparrowapp-dev/sparrow-app#1116]
**Description**:
Currently the user is not able to update the Sparrow application in windows machines. When the user clicks the update button then a new sparrow application is installed instead of updating the old one. There is an issue in the update of the application.

This task is created in order to debug and resolve the issue of update of the sparrow application.

**Comment by punitkashyup** [comment]
@pratikshinde590  Pls update your finding here .

**Comment by pratikshinde590** [comment]
we can convert the MSI to MSIX package using script: 
https://github.com/microsoft/MSIX-Toolkit/tree/master/Scripts
 
And we can use this script in our deployment workflow so this can automate the process of converting the MSI to MSIX.
 
After that we can publish our app to Microsoft store using this plugin in our workflow: 
https://github.com/marketplace/actions/microsoft-store-publish
 
then the same application we will release in our GitHub releases so that both app will be the same in git releases and windows store.

**Comment by Monika-APM** [comment]
Closing this ticket as we have pulled out our app from Microsoft store.
