### ISSUE TITLE
[Updater] Updater appears again and again after closing it 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1313]
### **🐛 Bug Report**

**Steps to reproduce:**
- Login to sparrow and click on cross button of updater
- Now perform come action in sparrow app

**Expected Behaviour:** After closing the update it should not appear again and again 

**Actual Behaviour:** If User do not want to update the app and want to stay in the previous version, so after closing the blue banner of updater its appears again and again when user perform actions on Sparrow.

**Comment by Abhishek9503** [comment]
This is not a bug , since the updater will be visible when the user opens the old version of app and if the user close the updater popup then  it will again visible  only when the app is restarted or  if we perform reload on the app , but the reload feature will only enbale for now it will not worki in the production so the possible scenario remaining is that if the user reopen the app after closing the update popup then only the update will visible to user .

CC:- @gc-codes    @LordNayan @shreyas070707  @sanilnayak  @Monika-APM

**Comment by sanilnayak** [comment]
Closing the issue
