### ISSUE TITLE
Test Flows - Delete option

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1402]
Description : In this, user should be able to edit the name of the test flow or user can also delete the block & test flow.

Figma/SS: NA

Acceptance criteria 1:[ Delete the block]
Given User wants to delete the selected block
When User clicks on three dots given in the block
Then User should be able to view the delete option. By clicking on delete the block should be deleted. 
Other delete options are:

1. On right of the block delete option should appear, from there should should be able to delete the block
2. User can also select the block & press delete key from the keyboard, then the selected block should be deleted.

Acceptance criteria 2:[Delete the test flow]
Given User wants to delete the entire test flow
When User clicks on three dots from the left of the test flow
Then User once hovers on the test flow three dots will appear & once he clicks on three dots he can select the delete option & user should be able to delete the test flow.

**Comment by sanilnayak** [comment]
### **In MAC:**

- AC1- 

Delete is working 

- AC2- 

https://github.com/user-attachments/assets/37e2baba-3bce-4012-8e71-f05ff2519d9d


### **Bugs Found by QA team:**

- Trying to Delete any selected block so its deleting the whole flow 
https://github.com/user-attachments/assets/fdfce81f-816b-4e66-8f5c-2b8c429831eb

- Even there is no any toast messages for delete block.
- User can also select the block & press delete key from the keyboard, then the selected block should be deleted - Not working

**Comment by Abhishek9503** [comment]
User can also select the block & press delete key from the keyboard, then the selected block should be deleted - Not working

We have prevent this thing in mac like on clicking delete button in mac the delete function will not work because on pressing delte button in  mac the app reloads, so for now we have prevented the delete button on mac , but user can delete the node from three dot on the node, the delete button will work on the windows fine.

CC ;- @sanilnayak  @Monika-APM @satya1602

**Comment by sanilnayak** [comment]
Then its working
