### ISSUE TITLE
Web App Workspace Flow

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1551]
Description : In this story, workspace is to be revamped, In the left panel below the team's dropdown workspace, members & settings options will be shown & by default workspace will be selected & shown to the user. There will be 4 columns shown to the user those are as follows : 

1. Workspace 
2. Collections
3. Contributors
4. Last updated

Figma/SS : 
<img width="505" alt="image" src="https://github.com/user-attachments/assets/8130df34-7684-40be-84a4-64cb9f0fbaee">

Acceptance criteria 1: [Hover state]
Given User is redirected to workspace page on web app
When User hovers on any of the available workspace
Then User should be able to see "Open in desktop" button & once he clicks on it he should be redirected to download the Sparrow app.

Note : 

1. All the other functionalities for : Search, Invite, New workspace, Layout & Pagination, will remain same as in Sparrow App.
2. If the Workspace is shared with others contributors column should be visible otherwise it will not be shown.

**Comment by sanilnayak** [comment]
### **Issues:**

- Ui is not as per figma

![Image](https://github.com/user-attachments/assets/0dc9a284-0ccd-4d7c-83f1-6572c51b09ce)

![Image](https://github.com/user-attachments/assets/9697ccad-26d6-4aa0-a1be-2520f84112c4)


These are the isseus @harshvardhan-212 please check

**Comment by shreyas070707** [comment]
Acceptance criteria 1: [Hover state]-Working
Given User is redirected to workspace page on web app
When User hovers on any of the available workspace
Then User should be able to see "Open in desktop" button & once he clicks on it he should be redirected to download the Sparrow app.
https://github.com/user-attachments/assets/15c9000f-ff26-4b91-8aea-5e5ecc913faa

All the other functionalities for : Search, Invite, New workspace, Layout & Pagination, will remain same as in Sparrow App.-Working

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EW2LfDo4Oe5Gob9TM7J9buwBr_Z1VrIXGz4z14o5VpvU4Q?e=Tc7gxw
If the Workspace is shared with others contributors column should be visible otherwise it will not be shown.-working
![Image](https://github.com/user-attachments/assets/d4c8de5d-5263-42a2-85a6-c56847b7e6ad)
@sanilnayak  please test for mac

**Comment by sanilnayak** [comment]
Working on Mac:

![image](https://github.com/user-attachments/assets/2beb76ec-ce30-4a11-a9d0-1d974e096311)

![image](https://github.com/user-attachments/assets/5a54011d-8df8-4a18-a342-45aafd2579a7)
