### ISSUE TITLE
Regression issues

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1801]
- [ ] #2022

- [ ] #2021
- [ ] #2020
- [x] As a viewer, there is a tooltip which is away from the box, also viewer is able to click on collection button it should be disabled
- [x] recent workspace is not working properly in home page(only recently created workspace are showing )

**Comment by Abhishek9503** [comment]
Comments:-
1. In the help section user is not able to understand the feedback is belongs to which categories example Feature request/UX improvement/Bugs======>>>>> I think this should be assinged to desgin team first then to developer .
2. Can we have separate story for mac issue .
3. the email icon issue we are not able to figure out the approach since email does not support the dom code and handle the black and white mode automatically.

Cc:- @sanilnayak @shreyas070707  @Monika-APM

**Comment by sanilnayak** [comment]
Its as per figma in mac 
![Image](https://github.com/user-attachments/assets/a2b8ce9c-7656-443b-b5f1-a5af922b61cc)

**Comment by satya1602** [comment]
Working in windows-

> As a viewer, there is a tooltip which is away from the box, also viewer is able to click on collection button it should be disabled.

![Image](https://github.com/user-attachments/assets/be2c03ce-1226-45ea-a802-acb891ca1076)

> Recent workspace is not working properly in home page(only recently created workspace are showing )

![Image](https://github.com/user-attachments/assets/78e8eb72-4df7-4ede-9e4c-f6127e0ec898)
