### ISSUE TITLE
In active sync, branch by-default changing to current branch again and again.

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#665]
### **🐛 Bug Report**

In active sync, the branch by default changes to the current branch repeatedly.

**Steps to reproduce:**

- Login to Sparrow and import a collection from the local host Swagger with different primary branch 
- Now from the dropdown switch branch to primary and navigate in-app randomly 
- Now go back to the collection and see the branch 

**Expected Behaviour:** Branch which was selected before, when the user came back to collection same branch should reflect.

**Actual Behaviour:** Branch is switching to default.

**Comment by shreyas070707** [comment]
After changing branch from default to another branch.
go to home
create workspace
again come back to same active sync collection

changed branch should appear instead of default branch.

 https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ETLPE3NzS8RNkRJYVUF5yHMBinvs9DH_g-PoYUiruI3ZSg?e=X9b9HC

**Comment by sanilnayak** [comment]
Not working in mac

**Comment by itsmdasifraza** [comment]
This is the expected behaviour, please confirm

**Comment by sanilnayak** [comment]
Working from my end @shreyas070707 please test

**Comment by shreyas070707** [comment]
working in windows
