### ISSUE TITLE
Save Request - Popup

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-app#898]
**Description:**
When the user clicks on the save button of an API request, a popup should appear, giving the user the option to select the location where they want to save the request. This popup should provide clear options for the user to choose from, ensuring they can save the request in the desired location.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/155429307/56a3059d-2f56-4e01-8e90-9f7d91b86fb2)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user wants to save an API request 
When the user has clicked Save icon / Save changes button
Then the user should be navigated to Save Request popup with the following elements
Left Pane:
Header Save Request.
List of workspaces below the header where the user can select a workspace of his choice (Currently only 1 workspace is available)
Workspace label with Name of the workspace. 
Informative text below the Workspace label.
List of collections in the workspace where the user can select a collection of his choice.
+ Collection (If the user is at a workspace level) or + Folder (If the user is at a collection and 1 down folder level) button at the bottom as per the process.

Right Pane:
Request Name header with a * mark showing its mandatory.
Icon displayed in order to guide the user with the best practices as in the figma.
Space to provide the Request Name.
Method type.
URL of the request.
Description label.
Space to provide the description text with the placeholder text. A user may provide description upto 200 characters.
Saving to label
Workspace/Collection/Folder name displayed as per figma. If the user is at the Workspace level and has not selected the collection yet, there should be an error in red stating Select a collection or Folder.
Button - Cancel to cancel the operation.
Button - Save to save the request and relevant details.

Success / Failure message should be displayed if the user is able to successfully save / if there is any error in saving.

Acceptance Criteria 2 [Save request validation error]:
Given the user wants to save a request
When the user is in the save request popup and clicks the save button without providing the request name or selecting the location of save
Then there should be a validation error displayed on the screen as per figma. The user should not be able to proceed without providing the request name or choosing the location.

**Comment by shreyas070707** [comment]
AC1-
Left Panel:
Header Save Request ****present****
List of workspaces below the header where the user can select a workspace of his choice (Currently only 1 workspace is available) **present**
Workspace label with Name of the workspace. **present**
Informative text below the Workspace label. **present**
List of collections in the workspace where the user can select a collection of his choice. **present**

Collection (If the user is at a workspace level) or + Folder (If the user is at a collection and 1 down folder level) button at the bottom as per the process. **present**
Right Panel:
Request Name header with a * mark showing its mandatory. **present**
Icon displayed in order to guide the user with the best practices as in the figma. **present**
Space to provide the Request Name. **present**
Method type. **present**
URL of the request. **present**
Description label. **present**
Space to provide the description text with the placeholder text. A user may provide description upto 200 characters. **present**
Saving to label **present**
Workspace/Collection/Folder name displayed as per figma. If the user is at the Workspace level and has not selected the collection yet, there should be an error in red stating Select a collection or Folder. **present**
Button - Cancel to cancel the operation. **present**
Button - Save to save the request and relevant details. **present**

Success / Failure message should be displayed if the user is able to successfully save / if there is any error in saving.**present**


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/5559383a-d69f-42a6-838c-1e8cf50f8e8c)

AC2-
Given the user wants to save a request
When the user is in the save request popup and clicks the save button without providing the request name or selecting the location of save
Then there should be a validation error displayed on the screen as per figma. The user should not be able to proceed without providing the request name or choosing the location.


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/55790a8b-3902-4a4e-bfe1-3ae63684eec6)

**Comment by sanilnayak** [comment]
Tested in mac and listed the bugs.
@shreyas070707  @jshalini26  please test on windows.
